name: frontend

on:
  push:
    

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
      - name: npm install
        run: cd frontend && npm install
      - name: lint
        run: cd frontend && npm run lint
      - name: lint-css
        continue-on-error: true
        run: cd frontend && npm run lint-css
    
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
      - name: npm install
        run: cd frontend && npm install
      - name: test
        run: cd frontend && npm run test:unit
  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
      - name: npm install
        run: cd frontend && npm install
      - name: Build
        run: cd frontend && npm run build